Jet Setter - Initial PR
dbuendia/jet-setter pull request #1
Opened 2022-09-23 15:12 UTC by dbuendia

<img width="1155" alt="Captura de Pantalla 2022-09-23 a las 17 11 06" src="https://user-images.githubusercontent.com/14167326/191993550-b0822eac-234e-48a1-b99a-b9a348f7266d.png">

Jet Setter PR with all requested features working.

Updated github page:
https://dbuendia.github.io/jet-setter/

2022-09-25 14:14 UTC, havebeeair requested changes
This work is GREAT!

2022-09-25 14:14 UTC, havebeeair commented on src/App.js
> +        value: value,
You can do just 'value' here. Javascript has a shortcut syntax where if the property has the same name of the value, then you can just type it once:
```
const updatedItems = [
    {
        value,
        id: items.length + 1
        ...
    }
]
```

2022-09-25 14:14 UTC, havebeeair commented on src/App.js
> +  items.filter((item) => {
Do we need a filter for this? Since this is not being returned (the filter) we can do a forEach.

2022-09-25 14:14 UTC, havebeeair commented on src/App.js
> +  const filterUnpackedItems = unpackedItems.filter((elem) => {
This is a correct use of filter ✅

2022-09-25 14:14 UTC, havebeeair commented on src/App.js
> +      return true;
You can also return the statement instead of doing a conditional, is less lines of code, and it's also semantic, like:
```
const filterUnpackedItems = unpackedItems.filter((elem) => {
    return elem.value.toUpperCase().indexOf(unpackedFilterInput.toUpperCase()) >= 0
})
```

2022-09-25 14:14 UTC, havebeeair commented on src/App.js
> +  const filterPackedItems = packedItems.filter((elem) => {
Same comment as before

2022-09-25 14:14 UTC, havebeeair commented on src/App.js
> +        return elem;
Remember that filters expect to return true or false, and if true, it will return the element into the array. You can either return true instead of `elem` or to do a one-liner, do `return elem.id !== id`

2022-09-25 14:14 UTC, havebeeair commented on src/App.js
> +        return elem;
This double `return elem` is a code smell. That's not a critic of your code, I'm just letting you know. You know that map expects to return an element yes or yes, unlike filter, so you could apply your transformation based on the conditional, and return the element after it. Something like:
```
const markedItems = items.map((elem) => {
      if (elem.id === id) {
        elem.packed = !elem.packed;
      } 
       return elem;
```
In this case, if the id doesn't match, the if won't apply and you still get the same element, unaltered.

2022-09-25 14:14 UTC, havebeeair commented on src/App.js
> +    console.log("daniell");
Remove useless console.logs

2022-09-25 14:14 UTC, havebeeair commented on src/App.js
> +        return elem;
Same comment as before with the double return here.

2022-09-25 14:14 UTC, havebeeair commented on src/components/AddElementBar.jsx
> +        name="new"
`new` is a very generic name for an input or variable. `newSearchInput` or something similar could work.

2022-09-25 14:14 UTC, havebeeair commented on src/components/AddElementBar.jsx
> +        onKeyPress={(e) => (e.key === "Enter" ? onClick(value, e) : null)}
Not mad at this one-liner, but i _think_ the body of the function doesn't need the parenthesis:
`onKeyPress={(e) => e.key === "Enter" ? onClick(value, e) : null}`

 Also, when a ternary is always returning `null` on their "false" side, you could use the double ampersand operator which acts a shortcut for the same line:

`onKeyPress={(e) => e.key === "Enter" && onClick(value, e)}`

The code below says if this is true, do this only.

2022-09-25 15:47 UTC, dbuendia commented on src/App.js
> +    setaddElementBarValue(e.target.value);
Interesting. I'll try to keep this in mind.

2022-09-25 15:50 UTC, dbuendia commented on src/App.js
> +  function onButtonClick(value, e) {
I wonder who wrote that.

2022-09-25 16:03 UTC, dbuendia commented on src/App.js
> +        value: value,
Aaaah, will definitely **not** remember that in the future. 👍🏻

2022-09-25 16:07 UTC, dbuendia commented on src/App.js
> +  const filterUnpackedItems = unpackedItems.filter((elem) => {
No wonder you suggested it 😂

2022-09-25 16:16 UTC, dbuendia commented on src/App.js
> +      return true;
I wouldn't agree that is more semantic, since it's such a long expression. I know it's basically saying if true then return true, but the if structure makes a bit clearer for me. I'll change it anyyway, but will leave a comment for myself in the future.

2022-09-25 16:42 UTC, dbuendia commented on src/App.js
> +    console.log("daniell");
My name is not useless.

2022-09-25 16:42 UTC, dbuendia commented on src/App.js
> +    console.log("daniell");
Yes I liked myself.

2022-09-29 00:50 UTC, havebeeair approved these changes
Ship it! 🚢

2022-09-29 10:52 UTC, merged